### ISSUE TITLE
Critical: Unable to add items

### ISSUE THREAD

**Issue by mxafi** [thingybase/community#16] opened 2022-10-29 11:48 UTC
### Steps to reproduce:

1. Create an account
2. Press "Add items"
3. Encounter error

### Screenshots
[https://imgur.com/a/mjHKKav](https://imgur.com/a/mjHKKav)

**Comment by bradgessler** [comment] 2022-10-29 16:31
Hi! Thanks for reporting this issue. I can't recreate it on any of my accounts, but I do see the error reports coming in from your account. I'm still investigating the cause, but I want to acknowledge the receipt of your report. I'll provide updates here as I work through the issue.

**Comment by bradgessler** [comment] 2022-10-29 16:41
Alrightly, found the root cause of the problem! When an account has 0 items in it, as yours did, it would assume there's a container name that it display in the UI telling you something like, "Your shelf is empty". Unfortunately when an account is completely empty, there's no container names around, which triggered the error.

I added a check to the UI that displays the account name (instead of the non-existent container name) so there wouldn't be an error.

Thanks so much for reporting this! I've deployed the fix and will close this issue. If you run into it again feel free to add another comment to this and I'll re-open it. If you run into any other issues then please open a different ticket.

**Closed by bradgessler** 2022-10-29 16:41 UTC
